from flask import Flask, render_template, request, jsonify
import threading
import time
import datetime
import re
import schedule
import pywhatkit
from pynput.mouse import Listener
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.common.exceptions import StaleElementReferenceException

app = Flask(__name__)

# --- Global State for Web Server ---
bot_state = {
    "is_running": False,
    "jobs_completed": 0,
    "logs": ["[SYSTEM] Server started. Ready to launch."]
}

def log_msg(message):
    current_time = datetime.datetime.now().strftime("%H:%M:%S")
    bot_state["logs"].append(f"[{current_time}] {message}")
    if len(bot_state["logs"]) > 50: # Keep only last 50 logs to save memory
        bot_state["logs"].pop(0)
    print(f"[{current_time}] {message}")

class MouseBlocker:
    def __init__(self):
        self.listener = None
    def __enter__(self):
        self.listener = Listener(suppress=True)
        self.listener.start()
        return self
    def __exit__(self, exc_type, exc_val, exc_tb):
        if self.listener:
            self.listener.stop()

def fetch_rates(silver_margin, gold_margin):
    log_msg("🚀 Starting Chrome in background...")
    service = Service(ChromeDriverManager().install())
    options = webdriver.ChromeOptions()
    options.add_argument('--headless')
    options.add_argument('--log-level=3')
    driver = webdriver.Chrome(service=service, options=options)
    
    silver_rate, gold_rate = "Not Found", "Not Found"

    try:
        log_msg("⏳ Fetching Silver rates...")
        driver.get("https://shreenavratnabullions.com/liverates.html")
        time.sleep(6)
        try:
            for tab in driver.find_elements(By.XPATH, "//*[text()='SILVER']"):
                if tab.is_displayed():
                    tab.click()
                    time.sleep(2)
                    break
        except: pass

        for _ in range(3):
            try:
                for row in driver.find_element(By.ID, "gvData_Trending_Silverr").find_elements(By.TAG_NAME, "tr"):
                    cols = row.find_elements(By.TAG_NAME, "td")
                    if len(cols) >= 3 and "SILVER" in cols[0].text.upper():
                        nums = re.findall(r'\b\d{5,7}\b', cols[2].text.replace(',', ''))
                        if nums:
                            silver_rate = int(nums[0]) + silver_margin
                            break
                if silver_rate != "Not Found": break
            except StaleElementReferenceException:
                time.sleep(2)

        log_msg("⏳ Fetching Gold rates...")
        driver.get("https://www.safaribullions.com/")
        time.sleep(6)

        for _ in range(3):
            try:
                for row in driver.find_element(By.ID, "gvData_Trending").find_elements(By.TAG_NAME, "tr"):
                    row_text = row.text.upper()
                    if "GOLD" in row_text and "995" in row_text:
                        cols = row.find_elements(By.TAG_NAME, "td")
                        if len(cols) >= 3:
                            nums = re.findall(r'\b\d{5,7}\b', cols[2].text.replace(',', ''))
                            if nums:
                                gold_rate = int(nums[0]) + gold_margin
                                break
                        else:
                            nums = re.findall(r'\b\d{5,7}\b', row_text.replace(',', ''))
                            if len(nums) >= 2:
                                gold_rate = int(nums[1]) + gold_margin
                                break
                if gold_rate != "Not Found": break
            except StaleElementReferenceException:
                time.sleep(2)
    except Exception as e:
        log_msg(f"⚠️ Scraping Error: {e}")
    finally:
        driver.quit()
        log_msg("🛑 Chrome browser closed.")

    return silver_rate, gold_rate

def execute_job(group_id, s_margin, g_margin, shift_name):
    log_msg(f"⏰ SCHEDULE ALERT! Starting {shift_name} process...")
    s_rate, g_rate = fetch_rates(s_margin, g_margin)
    
    msg_text = f"🎯 *{shift_name.upper()} UPDATE* 🎯\n\n🥈 *SILVER RATE* : ₹ {s_rate} /kg\n🥇 *GOLD RATE (24kt)* : ₹ {g_rate} /10 gm\n*GOLD RATE (22kt)* : ₹ {g_rate*0.92}/10gm \n\n_Generated by Bot 🤖_"
    
    log_msg("🚫 Mouse input disabled (Sending Message)...")
    try:
        with MouseBlocker(): 
            pywhatkit.sendwhatmsg_to_group_instantly(group_id, msg_text, wait_time=20, tab_close=True, close_time=3)
        log_msg("✅ Mouse input enabled!")
        log_msg("✅ Message sent successfully!")
    except Exception as e:
        log_msg(f"❌ Error in WhatsApp: {e}")

    bot_state["jobs_completed"] += 1
    log_msg(f"📊 Progress: {bot_state['jobs_completed']}/3 Updates Completed.")
    
    if bot_state["jobs_completed"] >= 3:
        log_msg("🎉 All 3 daily updates completed. Shutting down schedule.")
        bot_state["is_running"] = False
        schedule.clear()

def run_schedule(data):
    schedule.clear()
    
    g_id = data['group_id']
    s_m, g_m = int(data['s_margin']), int(data['g_margin'])
    t1, t2, t3 = data['time1'], data['time2'], data['time3']
    
    schedule.every().day.at(t1).do(execute_job, g_id, s_m, g_m, "Morning Update")
    schedule.every().day.at(t2).do(execute_job, g_id, s_m, g_m, "Afternoon Update")
    schedule.every().day.at(t3).do(execute_job, g_id, s_m, g_m, "Evening Update")
    
    log_msg(f"✅ Schedule set for {t1}, {t2}, {t3}.")
    log_msg("⏳ Bot is waiting in the background...")
    
    while bot_state["is_running"] and bot_state["jobs_completed"] < 3:
        schedule.run_pending()
        time.sleep(1)


# --- FLASK WEB ROUTES ---

@app.route('/')
def index():
    # Serves the HTML file
    return render_template('index.html')

@app.route('/start', methods=['POST'])
def start_bot():
    if not bot_state["is_running"]:
        data = request.json
        bot_state["is_running"] = True
        bot_state["jobs_completed"] = 0
        bot_state["logs"] = [] # Clear old logs
        log_msg("🚀 Starting Web Bot Engine...")
        
        # Start backend loop in a separate thread so web server doesn't freeze
        threading.Thread(target=run_schedule, args=(data,), daemon=True).start()
        return jsonify({"status": "started"}), 200
    return jsonify({"status": "already running"}), 400

@app.route('/stop', methods=['POST'])
def stop_bot():
    bot_state["is_running"] = False
    schedule.clear()
    log_msg("🛑 Bot Manually Stopped.")
    return jsonify({"status": "stopped"}), 200

@app.route('/logs', methods=['GET'])
def get_logs():
    # Frontend will ask for logs every second
    return jsonify({
        "logs": bot_state["logs"],
        "is_running": bot_state["is_running"]
    }), 200

if __name__ == "__main__":
    print("🌐 WEB SERVER RUNNING! Open http://127.0.0.1:5000 in your browser.")
    # Run the web server
    app.run(debug=True, port=5000, use_reloader=False)
    